#! /bin/bash -ex

#####################
# Configuration     # 							     
#####################

### Sources
UBOOT_VERSION="2015.01-rc1"
UBOOT_CONFIG="am335x_evm_defconfig"
SRC_DIR="src"
FIRMWARE_IMG="u-boot.bin MLO"

#####################
# Script            #
#####################

git clone -b ${UBOOT_VERSION} --depth 1 --single-branch $(git remote -v | sed -n '/.git/{p;q;}' | awk '{print $(NF-1)}') ${SRC_DIR} && . ${SRC_DIR}/build

build
