#! /bin/bash -e

#####################
# Configuration     # 							     
#####################

### Sources
UBOOT_VERSION="2015.01-rc1"
UBOOT_CONFIG="cm_fx6_defconfig"
UBOOT_IMG="u-boot.img"
FIRMWARE_IMG=cm-fx6-firmware

#####################
# Script            #
#####################
SRC_DIR="src"

CMD="git clone -b ${UBOOT_VERSION} --depth 1 --single-branch $(git remote -v | sed -n '/.git/{p;q;}' | awk '{print $(NF-1)}') ${SRC_DIR}"
echo "[INFO] ${CMD}"
${CMD}

CMD=". ${SRC_DIR}/build"
echo "[INFO] $CMD"
${CMD}

function pre_output {
  # http://www.compulab.co.il/utilite-computer/wiki/index.php/Utilite_U-Boot_firmware
  
  CMD="dd if=/dev/zero count=500 bs=1K | tr '\000' '\377' > ${SRC_DIR}/${FIRMWARE_IMG}"
  echo "[INFO] ${CMD}"
  ${CMD}
  
  CMD="dd if=${SRC_DIR}/SPL of=${SRC_DIR}/${FIRMWARE_IMG} bs=1K seek=1 conv=notrunc && dd if=${SRC_DIR}/${UBOOT_IMG} of=${SRC_DIR}/${FIRMWARE_IMG} bs=1K seek=64 conv=notrunc"
  echo "[INFO] ${CMD}"
  ${CMD}
}

build
